char palavraSecreta[20];
char letrasCertas[20];
int tentativas;
void escolhePalavra();
void adicionarPalavra();
void chutar();
void peencherChutesCertos(char, int);
int validarChute(char validador, int controlador);
void mostrarForca(int);
void mensagemInicio();
void mensagemFim();
